#! /bin/bash

OEROOT="`pwd`"
OE_CORE_SCRIPTS="`pwd`/layers/openembedded-core/scripts"
BITBAKE_SCRIPTS="`pwd`/bitbake/bin"

# Change PATH to make things more convenient.
export PATH="${OE_CORE_SCRIPTS}":"${BITBAKE_SCRIPTS}":"${PATH}"

# Allow to build for different MACHINE directly.
# This is mostly due to OpenXT using MACHINE like "images". That could/should
# be fixed somewhere down the line.
export BB_ENV_EXTRAWHITE="MACHINE DISTRO"

MANIFEST=".repo/manifests"

# Deploy configuration for bitbake/OE
mkdir -p conf
ln -sf "../${MANIFEST}/conf/local.conf" conf/local.conf
ln -sf "../${MANIFEST}/conf/bblayers.conf" conf/bblayers.conf

# Default MACHINE.
__DEFAULT_MACHINE="xenclient-dom0"
__DEFAULT_DISTRO="openxt-main"
cat > conf/auto.conf <<EOF
MACHINE ?= "${__DEFAULT_MACHINE}"
DISTRO ?= "${__DEFAULT_DISTRO}"
EOF

# Config depending on host build machine.
cat > conf/site.conf <<_EOF
SCONF_VERSION = "1"

# Where to store sources
DL_DIR = "${OEROOT}/downloads"

# Where to save shared state
SSTATE_DIR = "${OEROOT}/sstate-cache"

# Which files do we want to parse:
BBFILES ?= "${OEROOT}/layers/openembedded-core/meta/recipes-*/*/*.bb"

# OpenXT: Where To get the signing certificates.
OPENXT_CERTS_DIR ?= "${OEROOT}/oxt-certs"

# OpenXT: Use local mirrors.
OPENXT_GIT_MIRROR ?= "${OEROOT}/mirrors"
OPENXT_GIT_PROTOCOL ?= "file"
OPENXT_BRANCH ?= "master"
OPENXT_TAG ?= "master"
OPENXT_MIRROR ?= "http://mirror.openxt.org/"
_EOF
